name: CreateIssuesLabel
on: 
  push:
    tags:
      - V*
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v1
        id: tagName
      - name: GET TAG NAME 
        run: |
              echo "::set-env name=TAG_NAME::${{ steps.tagName.outputs.tag  }}"
              
      - uses: actions/checkout@v1
      - name: GET TAG SHA
        run: |
              echo "::set-env name=TAG_SHA::$(git rev-parse ${{ env.TAG_NAME }})"
       
      - name: GET TAG MESSAGE
        run: | 
              echo "::set-env name=TAG_MESSAGE::$(curl https://api.github.com/repos/AgendaDoi/GithubActionsTagLabelTest/git/tags/${{ env.TAG_SHA }}?access_token=${{ secrets.GITHUB_TOKEN }} | jq -r '."message"')"
     
      - name: CREATE LABEL
        run: curl -v -H 'Content-Type:application/json; charset=UTF-8' -H 'X-Accept:application/json' -X POST -d '{"name":"occurs Ver:${{ env.TAG_NAME }}","description":"${{ env.TAG_MESSAGE }}","color":"000000"}' https://api.github.com/repos/AgendaDoi/GithubActionsTagLabelTest/labels?access_token=${{ secrets.GITHUB_TOKEN }}
