name: Labeler
on: 
  push:
    tags:
      - V*
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v1
        id: tagName
      - name: Tag 
        run: |
              echo "::set-env name=TAG_NAME::${{ steps.tagName.outputs.tag  }}"
              
      - name: Echo
        run: | 
              echo "${{ env.TAG_MESSAGE }}"
              curl https://api.github.com/repos/AgendaDoi/GithubActionsTagLabelTest/git/tags/${{ github.sha }}?access_token=${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v1
  
      - name: label
        run: |
              echo "::set-env name=TAG_SHA::$(git rev-parse ${{ env.TAG_NAME }})"
              echo "::set-env name=TAG_MESSAGE::$(curl https://api.github.com/repos/AgendaDoi/GithubActionsTagLabelTest/git/tags/${{ env.TAG_SHA }}?access_token=${{ secrets.GITHUB_TOKEN }} | jq -r "message")"
              curl -v -H 'Content-Type:application/json; charset=UTF-8' -H 'X-Accept:application/json' -X POST -d '{"name":"${{ steps.tagName.outputs.tag }}","description":"${{ env.TAG_MESSAGE }}","color":"f29513"}' https://api.github.com/repos/AgendaDoi/GithubActionsTagLabelTest/labels?access_token=${{ secrets.GITHUB_TOKEN }}
       
      - name: Echo
        run: | 
              echo "${{ env.TAG_MESSAGE }}"
              curl https://api.github.com/repos/AgendaDoi/GithubActionsTagLabelTest/git/tags/${{ env.TAG_SHA }}?access_token=${{ secrets.GITHUB_TOKEN }}
